// <auto-generated />
namespace AspUploadSample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lasteditorandLastEditDateaddedtofilemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lasteditorandLastEditDateaddedtofilemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201803120827271_lasteditor and LastEditDate added to file model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
